# Example docker-compose file for BrainzBot
# Make sure that either environment variables for TOKEN and LISTENBRAINZ_TOKEN are set,
# or that you set them directly here.
#
# You may change the binding of the config.json file to point it to somewhere else.
# Make sure it exists and contains what's in config.json.example

services:
  brainzbot:
    image: ghcr.io/defvs/brainzbot:main
    environment:
      - TOKEN=${TOKEN}
      - DATABASE_URL=mongodb://mongodb:27017/brainzbot
      - LISTENBRAINZ_TOKEN=${LISTENBRAINZ_TOKEN}
    volumes: # Change the path before the `:` as needed
      - ./config.json:/usr/src/app/config.json
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
