version: '3.8'

services:
  brainzbot:
    image: ghcr.io/defvs/brainzbot:latest
    environment:
      - TOKEN=${TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - LISTENBRAINZ_TOKEN=${LISTENBRAINZ_TOKEN}
    volumes:
      - ./config.json:/usr/src/app/config.json
    ports:
      - "3000:3000"
